
baseurl: '/nyc-core-framework/docs/2.0'
permalink: pretty

exclude: ['readme.md']
  
collections:
  documentation:
    output: true
    permalink: /documentation/:path/
    order: 
      - get-started.html
